### ISSUE TITLE
Progress Report - 02/06/2014

### ISSUE THREAD

**Issue by ladislas** [OuiSkin/hexa#10]
**Recipients: @OuiSkin/owners @OuiSkin/advisors**

Un petit mail pour faire le résumé de mon boulot sur le Github aujourd'hui et pour voir la suite.
## Nettoyage de printemps

J'ai fait un grand ménage, et j'ai viré plein de choses. Donc si tu ne retrouves plus les choses comme elles étaient, c'est normal, continue de lire, tout est décrit.
## Libraries

J'ai rajouté des libs des futurs capteurs et je les ai écrites, sauf le `SteamSensor`, mais ça ne devrait pas être trop différent du `MoistureSensor` actuel.

Je m'en chargerai plus tard.

J'ai aussi ajouté la lib `Led` que j'ai reprise de celle de Moti et je lui ai enlevé les références à `ChibiOS/RT`.
## Tests

Pour les libraries, j'ai aussi fait des tests de compilation pour voir si le code était déjà exempt d'erreur de frappe et tout passe.

Les tests sont dans le dossier `test` et porte le même nom que la librairie qu'il teste.

Ce ne sont pas encore des `unit tests` en bonne et due forme, mais je ne suis pas sûr qu'actuellement il faille s'embêter avec ça et puis c'est toujours mieux que rien.

L'idée dans les tests et d'utiliser toutes les fonctions de la librairie et de voir si ça marche comme on veut, donc de rédiger un peu tous les cas d'usage.

Ca permet que si on fait de grosse modification de voir si le compilation passe toujours ou s'il y a des soucis dans le code.

Comme c'est séparé du reste, ça évite de creuser dans des endroits incongrus et on va plus vite.
## Sources

J'ai viré les deux sources qu'on avait et qui servait à rien et j'ai remplacé par le dossier `hexa/` avec à l'intérieur le fichier `hexa.cpp`.

Ce dossier est là pour contenir le code du projet en entier, c'est à dire ce qui tournera vraiment sur le produit final ou du moins sur le prototype.

Ce code n'est pas là pour faire des tests et ne doit être modifié que pour ajouter une fonction ou corriger un bug ou n'importe quoi d'autre, mais pas pour du développement pur.

Par contre dans le dossier `src/`, il est tout à fait possible d'ajouter d'autre dossier qui permette de travailler sur des parties précises, par exemple la manière de clignoter des leds en fonction du message, etc.

Si ça marche, ce sera intégré à `hexa.cpp`, mais seulement quand ça marche.
## Makefile

J'ai aussi ajouté un fichier `Makefile-Example.mk` à la racine du dossier `hexa/` qu'il suffit de copier là où on veut compiler. Il faudra modifier le `PROJECT_DIR` comme d'habitude, mais normalement rien de plus.
## RTOS

En nettoyant `Led` je me suis posé la question de si on devait garder un RTOS.

Je pense que la réponse est **non**, _pour le moment_.

Je m'explique : un RTOS c'est super mais c'est très complexe à utiliser. Dans l'absolu et l'immédiat, ça n'apportera rien si ce n'est une grosse prise de tête.

On part sur un produit qui fonctionne par actions successives et qui ne fait rien en parallèle. Ce n'est pas bien grave parce qu'il ne fait rien de compliqué ni de très long à chaque fois, donc si ça clignote en disant "je réfléchis" pendant 3 secondes avant de devenir vert pour dire "tu peux m'appliquer", ça ne tuera personne et ce sera plus facile pour tout le monde.

Si un jour on fait une machine de guerre, on se reposera la question, mais de toute manière _le besoin viendra tout seul..._
## Branches

Il y a maintenant 2 branch `dev` et `master`.

J'ai passé `dev` en branch principale car c'est sur elle que se fera tout le travail.

`master` sert à garder une version **stable** qui peut être utilisée telle quelle par un designer qui veut faire un test ou n'importe qui d'autre.

`dev` est, comme son nom l'indique, la branch de développement, c'est à dire que c'est là que les tests d'intégration se font. Si tout fonctionne, on la merge vers master et ça fait une nouvelle version stable.

Quand on veut ajouter une nouvelle fonction, disons le `SteamSensor`, je vais créer une nouvelle branche dédiées à ça qui va me permettre de cloisonner mon développement. Ca permet à la fois de ne pas faire de bêtises et ça permet une meilleure collaboration entre les développeurs qui savent exactement ce qui se fait sur quelle branche.
## Comment développer ?!

Donc en gros ça donne :

``` bash
$ git checkout -b SteamSensor-Implementation

# je code...
# ...

# je suis prêt à faire un commit
$ git add SteamSensor.h SteamSensor.cpp
$ git commit -m "implementation of SteamSensor Lib"

# si je veux mettre cette branche sur github pour y travailler
# à plusieurs par exemple
$ git push origin SteamSensor-Implementation

# maintenant j'ai fini de travailler je vais récupérer les changements
# que d'autres ont pu faire à dev pendant que je bossais de mon côté
$ git pull origin dev

# s'il y a des merge conflicts, je les résous proprement et
# sans stress, tout va bien se passer :)

```

Une fois que j'ai fini mon travail, et **vraiment une fois que j'ai fini** (après avoir `pull`er depuis `origin/dev`), je vais sur la page des [Pull Requests (PR)](https://github.com/OuiSkin/hexa/pulls) et je click sur [New pull request](https://github.com/OuiSkin/hexa/compare/).

Je choisis ensuite les branches que je veux merger, dans mon cas `dev` puis `SteamSensor-Implementation`. Et je click sur `Create Pull Request`.

Si j'ai bien fait mon travail, ça devrait se merger sans aucun soucis.

Sinon je fais les modifs qu'il faut et je re-push vers ma branch. La PR s'updatera toute seule et dira une fois que c'est bon.
## Et les `commit`s dans tout ça ?

C'est aussi très important de commiter souvent, dès qu'on a franchi une étape. C'est important que le commit soit sur une partie du code précise.

Ce qui veut dire **ne pas travailler sur 10 fichiers en même temps et changer tout partout pour après avoir la flemme de faire plusieurs commits et en sortir un gros qui s'appelle *"update all".***

C'est important :)

Tu peux regarder un peu ce que j'ai commité aujourd'hui, ça te donnera la mesure.

Le but de faire ça c'est de pouvoir facilement suivre le développement et retrouver rapidement l'apparition d'un bug.

Et puis c'est propre et c'est cool.
## Conclusion

Voila grosso modo les changements que j'ai fait.

Le but maintenant c'est de garder une certaine consistence et de ne pas faire de bêtises qui mélangerai tout.

Surtout il faut se parler, comme je l'ai fait tout à l'heure à propos du _point_ pour la température.

C'est comme ça qu'on prévient les erreurs :)

**Comment by BenCoDev** [comment]
J aurais bien fait de le relire avent de commit tout a l heure ...
